export enum Role {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  QA_MANAGER = 'QA_MANAGER',
  TEST_MANAGER = 'TEST_MANAGER',
  TEST_LEAD = 'TEST_LEAD',
  TESTER = 'TESTER',
  DEVELOPER = 'DEVELOPER',
  BUSINESS_ANALYST = 'BUSINESS_ANALYST',
  PRODUCT_OWNER = 'PRODUCT_OWNER',
  AUDITOR = 'AUDITOR',
  MANAGEMENT = 'MANAGEMENT',
}
